version: '3.8'
services:
  web:
    build: .
    command: gunicorn "app:create_app()" -b 0.0.0.0:5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: